"""
Topic clustering service — semantic label edition.

Takes per-segment embeddings from the FAISS index and groups them using:
  - KMeans  : deterministic, n_clusters configurable (default)
  - HDBSCAN : density-based, auto-discovers cluster count

Section C: Cluster labels are generated by the shared LLM (flan-t5) so
they reflect the actual discussion meaning instead of generic "Topic 0".
Falls back to centroid-based label if LLM is unavailable or fails.

Examples:
    "Topic 0"
    "Model Deployment Discussion"
    "Project Timeline Planning"
"""
from __future__ import annotations

import logging
from collections import defaultdict
from typing import List

import numpy as np
from sklearn.cluster import KMeans

from models.schemas import ClusterTopic, TranscriptSegment

logger = logging.getLogger(__name__)

try:
    import hdbscan
    _HDBSCAN_AVAILABLE = True
except ImportError:
    _HDBSCAN_AVAILABLE = False
    logger.info("hdbscan not installed - KMeans will be used as fallback.")


def _centroid_label(texts: List[str], embeddings: np.ndarray) -> str:
    """Fallback: sentence closest to cluster centroid, truncated to 60 chars."""
    centroid = embeddings.mean(axis=0)
    distances = np.linalg.norm(embeddings - centroid, axis=1)
    best = texts[int(distances.argmin())]
    return best[:60] + ("..." if len(best) > 60 else "")


def _llm_label(texts: List[str]) -> str:
    """
    Generate a semantic topic name using the shared LLM.

    Prompt asks for a concise 4-6 word title describing the discussion.
    Falls back to centroid label on any exception.
    """
    try:
        from services.llm import llm_service

        sample = "; ".join(t[:120] for t in texts[:3])
        prompt = (
            "In 4-6 words, what is the main topic being discussed "
            "in this meeting excerpt? Give only the topic name, no explanation.\n"
            f"Excerpt: {sample}\n"
            "Topic name:"
        )
        label = llm_service.generate(prompt, max_new_tokens=20, num_beams=2)
        label = label.strip().strip("\"'").strip()
        if len(label) >= 3:
            return label
    except Exception as exc:
        logger.warning(f"LLM topic labeling failed: {exc}")
    return ""


class TopicClusterer:
    """
    Clusters transcript segments into thematic groups with semantic labels.
    Input  : embeddings (N, dim) + TranscriptSegment list
    Output : List[ClusterTopic]
    """

    def cluster(
        self,
        segments: List[TranscriptSegment],
        embeddings: np.ndarray,
        method: str = "kmeans",
        n_clusters: int = 5,
    ) -> List[ClusterTopic]:
        n = len(segments)
        if n < 2:
            logger.warning("Not enough segments to cluster.")
            return []

        k = min(n_clusters, n)

        if method == "hdbscan" and _HDBSCAN_AVAILABLE:
            labels = self._hdbscan(embeddings)
        else:
            if method == "hdbscan":
                logger.warning("HDBSCAN not installed - falling back to KMeans.")
            labels = self._kmeans(embeddings, k)

        return self._build_topics(segments, embeddings, labels)

    @staticmethod
    def _kmeans(embeddings: np.ndarray, k: int) -> np.ndarray:
        km = KMeans(n_clusters=k, random_state=42, n_init="auto")
        return km.fit_predict(embeddings)

    @staticmethod
    def _hdbscan(embeddings: np.ndarray) -> np.ndarray:
        clusterer = hdbscan.HDBSCAN(min_cluster_size=3, metric="euclidean")
        return clusterer.fit_predict(embeddings)

    def _build_topics(
        self,
        segments: List[TranscriptSegment],
        embeddings: np.ndarray,
        labels: np.ndarray,
    ) -> List[ClusterTopic]:
        groups: dict[int, list] = defaultdict(list)
        for i, (seg, lbl) in enumerate(zip(segments, labels)):
            groups[int(lbl)].append((i, seg))

        topics: List[ClusterTopic] = []
        for cluster_id, items in sorted(groups.items()):
            if cluster_id == -1:          # HDBSCAN noise
                continue
            indices = [i for i, _ in items]
            segs = [s for _, s in items]
            cluster_embs = embeddings[indices]
            texts = [s.text for s in segs]

            # Try LLM semantic label; fall back to centroid-based
            label = _llm_label(texts) or _centroid_label(texts, cluster_embs)

            topics.append(
                ClusterTopic(
                    cluster_id=cluster_id,
                    label=label,
                    size=len(segs),
                    speakers=sorted({s.speaker for s in segs}),
                    sample_texts=texts[:3],
                    time_range={
                        "start": min(s.start_time for s in segs),
                        "end": max(s.end_time for s in segs),
                    },
                )
            )
        return topics


topic_clusterer = TopicClusterer()